In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,15,30,45,60,90])
arreglo_grados

array([ 0, 15, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.26179939, 0.52359878, 0.78539816, 1.04719755,
       1.57079633])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.25881905, 0.5       , 0.70710678, 0.8660254 ,
       1.        ])

In [5]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 9.65925826e-01, 8.66025404e-01, 7.07106781e-01,
       5.00000000e-01, 6.12323400e-17])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 2.67949192e-01, 5.77350269e-01, 1.00000000e+00,
       1.73205081e+00, 1.63312394e+16])

In [14]:
arreglo_random = np.random.randint(11) # [0,11[
arreglo_random

9

In [17]:
numero_random_negativo = np.random.randint(-9,2)
numero_random_negativo

-7

In [18]:
arreglo_random = np.random.randint(10,20,5)
arreglo_random

array([18, 15, 11, 15, 18])

In [22]:
np.random.rand(9)

array([0.16447119, 0.23694794, 0.66644117, 0.32923545, 0.47684329,
       0.60886716, 0.20655122, 0.63778494, 0.16799267])

In [20]:
np.random.rand(3,2) 

array([[0.41066396, 0.54798751],
       [0.1008998 , 0.38105959],
       [0.12382732, 0.4040741 ]])

In [23]:
np.average(arreglo_random)

15.4

In [24]:
np.mean(arreglo_random)

15.4

In [25]:
np.median(arreglo_random) #Mediana

15.0

In [26]:
np.std(arreglo_random) #Desviación Estándar

2.5768197453450252

In [27]:
np.var(arreglo_random)

6.640000000000001

In [28]:
arreglo_random.mean()

15.4